# Generated by Django 3.2.16 on 2022-11-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='query_number',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
    ]
