# Generated by Django 3.2.16 on 2022-11-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_query_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Queries'},
        ),
    ]
